"""
scalper/signals_v9.py — V9 Meta Strategy Signal Module.

V9 uses V2opt3 as its execution engine but adds a context-aware gate:
it consults a lookup table built from historical trades to penalize or
confirm entries based on the market context (time of day, asset, price bucket).

The lookup table is generated by build_v9_lookup.py from ~1,100 historical trades.
"""
import json
import os
from datetime import datetime, timezone

from scalper.signals import SignalResult

# ── Lazy-loaded lookup table ───────────────────────────────────
_LOOKUP_TABLE = None
_LOOKUP_PATH = os.path.join(os.path.dirname(__file__), "v9_lookup_table.json")

# ── Configuration ──────────────────────────────────────────────
PENALIZE_THRESHOLD_WR = 45     # WR below this → penalize (optimized from 50)
PENALIZE_FACTOR = 0.3           # Multiply score by this (optimized from 0.4)
BOOST_THRESHOLD_WR = 55         # Boost disabled (factor=1.0) but kept for future
BOOST_FACTOR = 1.0              # No boost — optimizer found it adds no value
BLOCK_THRESHOLD_WR = 10         # Only block extreme toxicity (optimized from 25)


def _load_lookup_table() -> dict:
    """Load the lookup table from disk (cached)."""
    global _LOOKUP_TABLE
    if _LOOKUP_TABLE is None:
        if os.path.exists(_LOOKUP_PATH):
            with open(_LOOKUP_PATH, "r", encoding="utf-8") as f:
                _LOOKUP_TABLE = json.load(f)
            print(f"  [V9-META] Loaded lookup table: {len(_LOOKUP_TABLE)} context keys")
        else:
            print(f"  [V9-META] WARNING: No lookup table found at {_LOOKUP_PATH}")
            print(f"  [V9-META] Run: python build_v9_lookup.py to generate it")
            _LOOKUP_TABLE = {}
    return _LOOKUP_TABLE


def classify_time_of_day(utc_hour: int) -> str:
    """
    Classify UTC hour into time-of-day bucket (CDT-based).
    
    UTC 5-13  → overnight  (12AM-8AM CDT)
    UTC 13-17 → morning    (8AM-12PM CDT)
    UTC 17-23 → afternoon  (12PM-6PM CDT)
    UTC 23-5  → evening    (6PM-12AM CDT)
    """
    if 5 <= utc_hour < 13:
        return "overnight"
    elif 13 <= utc_hour < 17:
        return "morning"
    elif 17 <= utc_hour < 23:
        return "afternoon"
    else:
        return "evening"


def classify_price(price: float) -> str:
    """Classify entry price into bucket."""
    if price < 0.30:
        return "extreme_low"
    elif price < 0.46:
        return "low"
    elif price <= 0.54:
        return "golden"
    elif price <= 0.65:
        return "high"
    else:
        return "extreme_high"


def compute_all_signals_v9(assets: list[str], markets: dict) -> dict[str, SignalResult]:
    """
    V9 Meta Strategy signal computation.
    
    1. Compute base signals using technical_v2 (same as V2opt3)
    2. For each asset, lookup the context in the historical table
    3. Apply confidence gate: penalize/boost/block based on historical WR
    
    Returns dict of {asset: SignalResult}
    """
    # ── 1. Base signals from technical_v2 ─────────────────────
    from scalper.signals_v2 import compute_all_signals_v2
    base_signals = compute_all_signals_v2(assets)
    
    # ── 2. Load lookup table ──────────────────────────────────
    lookup = _load_lookup_table()
    if not lookup:
        # No table → behave exactly like V2opt3
        return base_signals
    
    # ── 3. Context-aware gating ───────────────────────────────
    now = datetime.now(timezone.utc)
    tod = classify_time_of_day(now.hour)
    
    for asset in list(base_signals.keys()):
        sig = base_signals[asset]
        score = sig.score
        direction = sig.direction
        
        if abs(score) < 0.01:
            # No signal, nothing to gate
            continue
        
        # Get current price for this asset from markets
        price = _get_current_price(asset, direction, markets)
        bucket = classify_price(price) if price else "golden"  # default to golden if unknown
        
        # Build lookup key
        key = f"{tod}|{asset}|{bucket}"
        entry = lookup.get(key)
        
        if entry is None:
            # No data at all for this context — allow with caution
            _log_decision(asset, key, "NO_DATA", score, score, None)
            continue
        
        wr = entry.get("wr", 50)
        sample = entry.get("sample_size", 0)
        is_fallback = entry.get("is_fallback", True)
        winner = entry.get("winner", "V2opt3")
        
        original_score = score
        
        # ── Apply gates ───────────────────────────────────────
        if wr <= BLOCK_THRESHOLD_WR and sample >= 5:
            # Historically terrible context — block entry
            sig.score = 0.0
            _log_decision(asset, key, "BLOCKED", original_score, 0.0, entry)
            
        elif wr < PENALIZE_THRESHOLD_WR:
            # Below breakeven — penalize heavily
            new_score = round(score * PENALIZE_FACTOR, 4)
            sig.score = new_score
            _log_decision(asset, key, "PENALIZED", original_score, new_score, entry)
            
        elif wr >= BOOST_THRESHOLD_WR and not is_fallback:
            # High confidence historical context — mild boost
            new_score = round(score * BOOST_FACTOR, 4)
            sig.score = new_score
            _log_decision(asset, key, "BOOSTED", original_score, new_score, entry)
            
        else:
            # Neutral — pass through unchanged
            _log_decision(asset, key, "PASS", original_score, score, entry)
    
    return base_signals


def _get_current_price(asset: str, direction: str, markets: dict) -> float | None:
    """Get the current polymarket price for an asset."""
    for key, mkt in markets.items():
        if asset.upper() in key.upper():
            if direction == "UP" or direction == "NEUTRAL":
                return mkt.get("up_price", mkt.get("yes_price"))
            else:
                return mkt.get("down_price", mkt.get("no_price"))
    return None


def _log_decision(
    asset: str,
    key: str,
    action: str,
    original_score: float,
    final_score: float,
    entry: dict | None,
):
    """Log V9 meta-strategy decision to console."""
    if entry:
        wr = entry.get("wr", "?")
        n = entry.get("sample_size", "?")
        winner = entry.get("winner", "?")
        fb = " (fallback)" if entry.get("is_fallback") else ""
        print(
            f"  [V9-META] {asset} | {key} | "
            f"WR={wr}% N={n} -> {winner}{fb} | "
            f"Action={action} | score {original_score:+.3f} -> {final_score:+.3f}"
        )
    else:
        print(
            f"  [V9-META] {asset} | {key} | "
            f"NO HISTORICAL DATA | "
            f"Action={action} | score {original_score:+.3f}"
        )
